version: "3.8"

services:

  rabbitmq_dev:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - dkb_dev

  db_dev:
    container_name: db_dev
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW} 
    ports:
      - 5432:5432
    restart: always
    networks:
      - dkb_dev
    volumes:
      - ./containers_data/db:/var/lib/postgresql/data
      - ./DB_SERVICE:/docker-entrypoint-initdb.d
  
  vk_api_send_dev:
    container_name: vk_api_send_dev
    build:
      context: ./VK_API_SEND_SERVICE
    restart: always
    networks:
      - dkb_dev
    ports:
      - 7331:7331
    environment:
      - DEBUG=${DEBUG}
      - PRODIGY=${PRODIGY}
      - LOCAL=${LOCAL}
    depends_on:
      - rabbitmq
    
  vk_daily_dev:
    container_name: dick_kraft_bot_vk_daily_dev
    build:
      context: ./VK_DAILY_SERVICE
    restart: always
    networks:
      - dkb_dev
    environment:
      - DEBUG=${DEBUG}
      - PRODIGY=${PRODIGY}
      - LOCAL=${LOCAL}
    depends_on:
      - db
      - rabbitmq

  event_handler_dev:
    container_name: event_handler_dev
    build:
      context: ./EVENT_HANDLER_SERVICE
    restart: always
    networks:
      - dkb_dev
    environment:
      - DEBUG=${DEBUG}
      - PRODIGY=${PRODIGY}
      - LOCAL=${LOCAL}
    depends_on:
      - db
      - rabbitmq

  vk_api_event_dev:
    container_name: vk_api_event_dev
    build:
      context: ./VK_API_EVENT_SERVICE
    restart: always
    networks:
      - dkb_dev
    environment:
      - DEBUG=${DEBUG}
      - PRODIGY=${PRODIGY}
      - LOCAL=${LOCAL}
    depends_on:
      - db
      - rabbitmq

  pgadmin_dev:
    container_name: pgadmin_dev
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PW} 
    ports:
      - 5050:80
    restart: always
    networks:
      - dkb_dev
    user: "${UID}:${GID}"
    volumes:
      - ./containers_data/pgadmin:/var/lib/pgadmin
    depends_on:
      - db

networks:
  dkb_dev:
    driver: bridge