global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'event_service'
    static_configs:
      - targets: ['event_handler_dev:8000']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq_dev:15692']
  - job_name: 'vk_api_send'
    scrape_interval: 5s
    static_configs:
      - targets: ['vk_api_send_dev:8000']
  - job_name: 'tg_api'
    scrape_interval: 5s
    static_configs:
      - targets: ['tg_api_event_dev:8000']

