version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management 
    ports:
      - "5672:5672"
      - "15672:15672"

  python_receiver:
    build: ./receiver
    depends_on:
      - rabbitmq

  python_sender:
    build: ./sender
    depends_on:
      - rabbitmq